name: Build application

on:
  push:
    branches:
      - develop

jobs:
  build-app:
    environment: development
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Notify Discord (Build Started)
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"username": "Bot GitHub", "content": "🚀 **Build iniciado!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nTag: `${{ github.ref_name }}`"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }} || true
    
    - name: Notify Telegram (Build Started)
      run: |
        curl -s -X POST \
        https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="🚀 **Build iniciado!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nTag: `${{ github.ref_name }}`" || true

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
         node-version: '18.x'

    - name: Install dependencies
      run: npm install --force

    - name: Prebuild Angular App
      run: npm run build-prod
      env:
        APP_DEBUG: production
        APP_NAME: ${{ github.repository }}
        APP_VERSION: ${{ github.ref_name }} 
        APP_AVATAR_IMG: ${{ secrets.APP_AVATAR_IMG }}
        APP_CV_FILE: ${{ secrets.APP_CV_FILE }}
  
    - name: Build Angular App
      run: npm run build -- --configuration=production 

    - name: Install firebase tools
      run: npm install -g firebase-tools
  
    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --token="${{ secrets.FIREBASE_TOKEN }}" --project="${{ secrets.FIREBASE_PROJECT_ID }}"

  notify-build-success:
    needs: build-app
    environment: production
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Notify Discord (Success)
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"username": "Bot GitHub", "content": "✅ **Sucesso ao gerar versão!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nTag: `${{ github.ref_name }}`"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Telegram (Success)
        run: |
          curl -s -X POST \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ **Sucesso ao gerar versão!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nTag: `${{ github.ref_name }}`"

  notify-build-failure:
    needs: build-app
    environment: production
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify Discord (Failure)
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"username": "Bot GitHub", "content": "❌ **Falha ao gerar versão!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nTag: `${{ github.ref_name }}`"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Telegram (Failure)
        run: |
          curl -s -X POST \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="❌ **Falha ao gerar versão!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nTag: `${{ github.ref_name }}`"