name: Notificar deploy da aplicação

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'development' || 'production' }}

    steps:
    - name: Notify Telegram (Deploy Started)
      run: |
        curl -s -X POST \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🚀 **Deploy iniciado na AWS!**\nRepositório: `${{ github.repository }}`\nAmbiente: ${{ github.ref == 'refs/heads/main' && 'Desenvolvimento' || 'Produção' }}\nTag: `${{ github.ref_name }}`"