name: Notificar deploy da aplicação

on:
  push:
    branches: ['main', 'firebase', 'aws-storage']
    tags:
      - 'v*'

jobs:
  notify-deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Notify Discord (Deploy Started)
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username": "Bot ${{ github.ref }}", "content": "🚀 **Deploy iniciado!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nTag: `${{ github.ref_name }}`"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
    
    - name: Notify Telegram (Deploy Started)
      run: |
        curl -s -X POST \
        https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="🚀 **Deploy iniciado!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nTag: `${{ github.ref_name }}`"