name: Notificar deploy da aplicação

on:
  push:
    branches:
        - 'main'
    tags:
      - 'v*'

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'development' || 'production' }}

    steps:
    - name: Notify Discord (Deploy Started)
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username": "Bot ${{ github.ref }}", "content": "🚀 **Deploy iniciado na AWS!**\nRepositório: `${{ github.repository }}`\nAmbiente: ${{ github.ref == 'refs/heads/main' && 'Desenvolvimento' || 'Produção' }}\nTag: `${{ github.ref_name }}`"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}